// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthURL() {
  return window['go']['services']['AuthService']['GetAuthURL']();
}

export function SetAuthConf() {
  return window['go']['services']['AuthService']['SetAuthConf']();
}
